// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viblobbjoqxmucpfvxln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYmxvYmJqb3F4bXVjcGZ2eGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzg1NjgsImV4cCI6MjA2MDcxNDU2OH0.qod73MrzKBqqoZdecF4cdllsMggsqEZ3i-Z4gSWros4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);